<?php

namespace App\Services;

use App\Models\ErpClient;
use App\Models\ErpFamily;
use App\Models\ErpInvoice;
use App\Models\ErpProduct;
use App\Models\ErpSale;
use App\Models\ErpSaleLine;
use App\Models\ErpSeller;
use App\Models\ErpStock;
use App\Models\ErpStockMovement;
use App\Models\ErpSubfamily;
use App\Models\ErpSupplier;
use App\Models\ErpWarehouse;

class ErpImportRegistry
{
    public static function all(): array
    {
        return [
            'familias' => [
                'model' => ErpFamily::class,
                'mapping' => [
                    'cod_familia' => 'cod_familia',
                    'descripcion' => 'descripcion',
                    'codigo_contable_compras' => 'codigo_contable_compras',
                    'codigo_contable_ventas' => 'codigo_contable_ventas',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_familia'],
            ],
            'subfamilias' => [
                'model' => ErpSubfamily::class,
                'mapping' => [
                    'cod_familia' => 'cod_familia',
                    'cod_subfamilia' => 'cod_subfamilia',
                    'descripcion' => 'descripcion',
                    'incremento' => 'incremento',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_familia', 'cod_subfamilia'],
            ],
            'almacenes' => [
                'model' => ErpWarehouse::class,
                'mapping' => [
                    'cod_almacen' => 'cod_almacen',
                    'nombre' => 'nombre',
                    'direccion1' => 'direccion1',
                    'direccion2' => 'direccion2',
                    'cp' => 'cp',
                    'poblacion' => 'poblacion',
                    'provincia' => 'provincia',
                    'cod_pais' => 'cod_pais',
                    'telefono' => 'telefono',
                    'fax' => 'fax',
                    'email' => 'email',
                    'persona_contacto' => 'persona_contacto',
                    'fecha_ultimo_inventario' => 'fecha_ultimo_inventario',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_almacen'],
            ],
            'vendedores' => [
                'model' => ErpSeller::class,
                'mapping' => [
                    'cod_vendedor' => 'cod_vendedor',
                    'nombre' => 'nombre',
                    'direccion1' => 'direccion1',
                    'cp' => 'cp',
                    'poblacion' => 'poblacion',
                    'provincia' => 'provincia',
                    'telefono' => 'telefono',
                    'fax' => 'fax',
                    'e_mail' => 'e_mail',
                    'seguridad_social' => 'seguridad_social',
                    'mutua' => 'mutua',
                    'comision_general' => 'comision_general',
                    'aniversario' => 'aniversario',
                    'observaciones' => 'observaciones',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_vendedor'],
            ],
            'clientes' => [
                'model' => ErpClient::class,
                'mapping' => [
                    'cod_cliente' => 'cod_cliente',
                    'nombre_comercial' => 'nombre_comercial',
                    'razon_social' => 'razon_social',
                    'cif' => 'cif',
                    'direccion1' => 'direccion1',
                    'direccion2' => 'direccion2',
                    'CP' => 'cp',
                    'poblacion' => 'poblacion',
                    'provincia' => 'provincia',
                    'cod_pais' => 'cod_pais',
                    'cod_idioma' => 'cod_idioma',
                    'cod_divisa' => 'cod_divisa',
                    'cod_tipo_cliente' => 'cod_tipo_cliente',
                    'telefono' => 'telefono',
                    'fax' => 'fax',
                    'e_mail' => 'e_mail',
                    'cod_forma_liquidacion' => 'cod_forma_liquidacion',
                    'dia_pago1' => 'dia_pago1',
                    'dia_pago2' => 'dia_pago2',
                    'dia_pago3' => 'dia_pago3',
                    'limite_credito' => 'limite_credito',
                    'moroso' => 'moroso',
                    'cod_banco' => 'cod_banco',
                    'direccion_banco1' => 'direccion_banco1',
                    'cp_banco' => 'cp_banco',
                    'poblacion_banco' => 'poblacion_banco',
                    'ccc' => 'ccc',
                    'iban' => 'iban',
                    'swift' => 'swift',
                    'dto_pronto_pago' => 'dto_pronto_pago',
                    'plazo_entrega' => 'plazo_entrega',
                    'cod_vendedor' => 'cod_vendedor',
                    'comision' => 'comision',
                    'fecha_alta' => 'fecha_alta',
                    'fecha_baja' => 'fecha_baja',
                    'cod_zona' => 'cod_zona',
                    'cod_estado_cliente' => 'cod_estado_cliente',
                    'cod_ruta' => 'cod_ruta',
                    'tipo_operacion_iva' => 'tipo_operacion_iva',
                    'ventas_credito_contado' => 'ventas_credito_contado',
                    'iva_incluido_ventas' => 'iva_incluido_ventas',
                    'latitud' => 'latitud',
                    'longitud' => 'longitud',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_cliente'],
            ],
            'articulos' => [
                'model' => ErpProduct::class,
                'mapping' => [
                    'cod_articulo' => 'cod_articulo',
                    'marca' => 'marca',
                    'cod_barras' => 'cod_barras',
                    'cod_familia' => 'cod_familia',
                    'cod_subfamilia' => 'cod_subfamilia',
                    'cod_impuesto' => 'cod_impuesto',
                    'unidades_venta' => 'unidades_venta',
                    'cod_unidad' => 'cod_unidad',
                    'cod_proveedor_activo' => 'cod_proveedor_activo',
                    'fecha_alta' => 'fecha_alta',
                    'fecha_baja' => 'fecha_baja',
                    'precio_coste' => 'precio_coste',
                    'incremento' => 'incremento',
                    'incremento_minimo' => 'incremento_minimo',
                    'cargo' => 'cargo',
                    'precio_venta_base' => 'precio_venta_base',
                    'precio_venta_publico' => 'precio_venta_publico',
                    'precio_medio_ponderado' => 'precio_medio_ponderado',
                    'descuento_maximo' => 'descuento_maximo',
                    'cod_gama' => 'cod_gama',
                    'peso_web' => 'peso_web',
                    'alto_web' => 'alto_web',
                    'ancho_web' => 'ancho_web',
                    'profundo_web' => 'profundo_web',
                    'tipo_articulo' => 'tipo_articulo',
                    'advertencia' => 'advertencia',
                    'observaciones' => 'observaciones',
                    'imagen' => 'imagen',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_articulo'],
            ],
            'ventas_cabecera' => [
                'model' => ErpSale::class,
                'mapping' => [
                    'cod_venta' => 'cod_venta',
                    'tipo_venta' => 'tipo_venta',
                    'cod_empresa' => 'cod_empresa',
                    'cod_caja' => 'cod_caja',
                    'cod_almacen' => 'cod_almacen',
                    'cod_cliente' => 'cod_cliente',
                    'nombre_comercial' => 'nombre_comercial',
                    'razon_social' => 'razon_social',
                    'cif' => 'cif',
                    'direccion1' => 'direccion1',
                    'cp' => 'cp',
                    'poblacion' => 'poblacion',
                    'provincia' => 'provincia',
                    'cod_pais' => 'cod_pais',
                    'cod_divisa' => 'cod_divisa',
                    'impuestos_incluidos' => 'impuestos_incluidos',
                    'cambio' => 'cambio',
                    'fecha_venta' => 'fecha_venta',
                    'hora_venta' => 'hora_venta',
                    'cod_forma_liquidacion' => 'cod_forma_liquidacion',
                    'cod_vendedor' => 'cod_vendedor',
                    'nombre_vendedor' => 'nombre_vendedor',
                    'su_pedido' => 'su_pedido',
                    'importe_cobrado' => 'importe_cobrado',
                    'importe_pendiente' => 'importe_pendiente',
                    'facturado' => 'facturado',
                    'importe' => 'importe',
                    'importe_impuestos' => 'importe_impuestos',
                    'estado_venta' => 'estado_venta',
                    'anulada' => 'anulada',
                    'cod_factura_asignada' => 'cod_factura_asignada',
                    'fecha_entrega' => 'fecha_entrega',
                    'cod_arqueo' => 'cod_arqueo',
                    'peso_total' => 'peso_total',
                    'reparto' => 'reparto',
                    'cod_ruta' => 'cod_ruta',
                    'cod_transportista' => 'cod_transportista',
                    'bulbos' => 'bulbos',
                    'dto_pronto_pago' => 'dto_pronto_pago',
                    'cargo_financiacion' => 'cargo_financiacion',
                    'importe_financiacion' => 'importe_financiacion',
                    'historico' => 'historico',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_venta', 'tipo_venta', 'cod_empresa', 'cod_caja'],
            ],
            'ventas_linea' => [
                'model' => ErpSaleLine::class,
                'mapping' => [
                    'cod_venta' => 'cod_venta',
                    'tipo_venta' => 'tipo_venta',
                    'cod_empresa' => 'cod_empresa',
                    'cod_caja' => 'cod_caja',
                    'linea' => 'linea',
                    'cod_articulo' => 'cod_articulo',
                    'descripcion' => 'descripcion',
                    'cantidad' => 'cantidad',
                    'dto1' => 'dto1',
                    'dto2' => 'dto2',
                    'precio' => 'precio',
                    'precio_coste' => 'precio_coste',
                    'cargo' => 'cargo',
                    'importe' => 'importe',
                    'importe_impuestos' => 'importe_impuestos',
                    'cod_impuesto' => 'cod_impuesto',
                    'porcentaje' => 'porcentaje',
                    'inventariable' => 'inventariable',
                    'cod_unidad' => 'cod_unidad',
                    'kit' => 'kit',
                    'unidades_venta' => 'unidades_venta',
                    'precio_venta_base' => 'precio_venta_base',
                    'precio_venta_publico' => 'precio_venta_publico',
                    'estado_venta' => 'estado_venta',
                    'descuento_maximo' => 'descuento_maximo',
                    'cod_barras' => 'cod_barras',
                    'cod_almacen' => 'cod_almacen',
                    'fecha_entrega' => 'fecha_entrega',
                    'observacion' => 'observacion',
                    'peso_unitario' => 'peso_unitario',
                    'peso_total' => 'peso_total',
                    'cod_tarifa' => 'cod_tarifa',
                    'version' => 'version',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_venta', 'tipo_venta', 'cod_empresa', 'cod_caja', 'linea'],
            ],
            'facturas_ventas_cabecera' => [
                'model' => ErpInvoice::class,
                'mapping' => [
                    'cod_factura' => 'cod_factura',
                    'tipo_factura' => 'tipo_factura',
                    'cod_empresa' => 'cod_empresa',
                    'cod_caja' => 'cod_caja',
                    'cod_cliente' => 'cod_cliente',
                    'cod_seccion' => 'cod_seccion',
                    'nombre_seccion' => 'nombre_seccion',
                    'cif' => 'cif',
                    'razon_social' => 'razon_social',
                    'nombre_comercial' => 'nombre_comercial',
                    'direccion1' => 'direccion1',
                    'direccion2' => 'direccion2',
                    'cp' => 'cp',
                    'poblacion' => 'poblacion',
                    'provincia' => 'provincia',
                    'cod_idioma' => 'cod_idioma',
                    'cod_pais' => 'cod_pais',
                    'cod_divisa' => 'cod_divisa',
                    'cambio' => 'cambio',
                    'impuestos_incluidos' => 'impuestos_incluidos',
                    'importe' => 'importe',
                    'importe_impuestos' => 'importe_impuestos',
                    'importe_divisa' => 'importe_divisa',
                    'importe_divisa_impuestos' => 'importe_divisa_impuestos',
                    'importe_cobrado' => 'importe_cobrado',
                    'importe_divisa_cobrado' => 'importe_divisa_cobrado',
                    'factura_oficial' => 'factura_oficial',
                    'cod_almacen' => 'cod_almacen',
                    'cargo_financiacion' => 'cargo_financiacion',
                    'importe_financiacion' => 'importe_financiacion',
                    'importe_divisa_financiacion' => 'importe_divisa_financiacion',
                    'tipo_factura_rectificada' => 'tipo_factura_rectificada',
                    'cod_factura_rectificada' => 'cod_factura_rectificada',
                    'fecha_factura_rectificada' => 'fecha_factura_rectificada',
                    'retencion_irpf' => 'retencion_irpf',
                    'importe_retencion_irpf' => 'importe_retencion_irpf',
                    'importe_divisa_retencion_irpf' => 'importe_divisa_retencion_irpf',
                    'cod_arqueo' => 'cod_arqueo',
                    'cod_primera_venta' => 'cod_primera_venta',
                    'cod_ultima_venta' => 'cod_ultima_venta',
                    'tipo_operacion_iva' => 'tipo_operacion_iva',
                    'cod_proveedor_otorgado' => 'cod_proveedor_otorgado',
                    'referencia_contrato_facturae' => 'referencia_contrato_facturae',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_factura', 'tipo_factura', 'cod_empresa', 'cod_caja'],
            ],
            'stocks' => [
                'model' => ErpStock::class,
                'mapping' => [
                    'cod_almacen' => 'cod_almacen',
                    'cod_articulo' => 'cod_articulo',
                    'existencias' => 'existencias',
                    'fecha_ultima_entrada' => 'fecha_ultima_entrada',
                    'fecha_ultima_salida' => 'fecha_ultima_salida',
                    'maximos' => 'maximos',
                    'minimos' => 'minimos',
                    'ubicacion' => 'ubicacion',
                    'fecha_ultimo_inventario' => 'fecha_ultimo_inventario',
                    'hora_ultimo_inventario' => 'hora_ultimo_inventario',
                    'permitir_venta_bajo_stock' => 'permitir_venta_bajo_stock',
                    'cantidad_pendiente_servir' => 'cantidad_pendiente_servir',
                    'cantidad_pendiente_recibir' => 'cantidad_pendiente_recibir',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_almacen', 'cod_articulo'],
            ],
            'proveedores' => [
                'model' => ErpSupplier::class,
                'mapping' => [
                    'cod_proveedor' => 'cod_proveedor',
                    'nombre_comercial' => 'nombre_comercial',
                    'razon_social' => 'razon_social',
                    'cif' => 'cif',
                    'codigo_contable' => 'codigo_contable',
                    'contrapartida' => 'contrapartida',
                    'direccion1' => 'direccion1',
                    'direccion2' => 'direccion2',
                    'cod_idioma' => 'cod_idioma',
                    'cod_divisa' => 'cod_divisa',
                    'cp' => 'cp',
                    'poblacion' => 'poblacion',
                    'provincia' => 'provincia',
                    'cod_pais' => 'cod_pais',
                    'telefono' => 'telefono',
                    'fax' => 'fax',
                    'e_mail' => 'e_mail',
                    'www' => 'www',
                    'fecha_alta' => 'fecha_alta',
                    'fecha_baja' => 'fecha_baja',
                    'credito_otorgado' => 'credito_otorgado',
                    'cod_condiciones_compra' => 'cod_condiciones_compra',
                    'cod_forma_liquidacion' => 'cod_forma_liquidacion',
                    'cod_banco' => 'cod_banco',
                    'direccion_banco1' => 'direccion_banco1',
                    'direccion_banco2' => 'direccion_banco2',
                    'cp_banco' => 'cp_banco',
                    'poblacion_banco' => 'poblacion_banco',
                    'cod_pais_banco' => 'cod_pais_banco',
                    'ccc' => 'ccc',
                    'plazo_entrega' => 'plazo_entrega',
                    'cod_transportista' => 'cod_transportista',
                    'cod_central_compras' => 'cod_central_compras',
                    'fecha_inicio_vacaciones' => 'fecha_inicio_vacaciones',
                    'fecha_fin_vacaciones' => 'fecha_fin_vacaciones',
                    'facturacion_centralizada' => 'facturacion_centralizada',
                    'observaciones' => 'observaciones',
                    'advertencia' => 'advertencia',
                    'portes_pagados' => 'portes_pagados',
                    'compra_minima' => 'compra_minima',
                    'su_cliente' => 'su_cliente',
                    'cliente_central_compra' => 'cliente_central_compra',
                    'dia_pago1' => 'dia_pago1',
                    'dia_pago2' => 'dia_pago2',
                    'dia_pago3' => 'dia_pago3',
                    'dia_vencimiento_vacaciones' => 'dia_vencimiento_vacaciones',
                    'gln_facturas' => 'gln_facturas',
                    'gln_pedidos' => 'gln_pedidos',
                    'iban' => 'iban',
                    'swift' => 'swift',
                    'criterio_de_caja' => 'criterio_de_caja',
                    'tipo_persona' => 'tipo_persona',
                    'motivo_baja' => 'motivo_baja',
                    'telefono2' => 'telefono2',
                    'telefono3' => 'telefono3',
                    'telefono1_comentario' => 'telefono1_comentario',
                    'telefono2_comentario' => 'telefono2_comentario',
                    'telefono3_comentario' => 'telefono3_comentario',
                    'fax_comentario' => 'fax_comentario',
                    'facebook' => 'facebook',
                    'twitter' => 'twitter',
                    'youtube' => 'youtube',
                    'whatsapp' => 'whatsapp',
                    'latitud' => 'latitud',
                    'longitud' => 'longitud',
                    'tipo_operacion_iva' => 'tipo_operacion_iva',
                    'inversion_sujeto_pasivo' => 'inversion_sujeto_pasivo',
                    'importe_portes_pagados' => 'importe_portes_pagados',
                    'valoracion_albaran' => 'valoracion_albaran',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_proveedor'],
            ],
            'movimiento_stock' => [
                'model' => ErpStockMovement::class,
                'mapping' => [
                    'cod_articulo' => 'cod_articulo',
                    'cod_empresa' => 'cod_empresa',
                    'cod_documento' => 'cod_documento',
                    'tipo_documento' => 'tipo_documento',
                    'cod_caja' => 'cod_caja',
                    'operacion' => 'operacion',
                    'cod_cliente' => 'cod_cliente',
                    'cod_proveedor' => 'cod_proveedor',
                    'fecha' => 'fecha',
                    'hora' => 'hora',
                    'cod_almacen' => 'cod_almacen',
                    'cantidad' => 'cantidad',
                    'linea' => 'linea',
                    'cod_movimiento' => 'cod_movimiento',
                    'linea_kit' => 'linea_kit',
                    'rowguid' => 'rowguid',
                ],
                'unique_by' => ['cod_movimiento'],
            ],
        ];
    }
}
