<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ErpSupplier extends Model
{
    protected $table = 'erp_suppliers';

    protected $fillable = [
        'cod_proveedor',
        'nombre_comercial',
        'razon_social',
        'cif',
        'codigo_contable',
        'contrapartida',
        'direccion1',
        'direccion2',
        'cod_idioma',
        'cod_divisa',
        'cp',
        'poblacion',
        'provincia',
        'cod_pais',
        'telefono',
        'fax',
        'e_mail',
        'www',
        'fecha_alta',
        'fecha_baja',
        'credito_otorgado',
        'cod_condiciones_compra',
        'cod_forma_liquidacion',
        'cod_banco',
        'direccion_banco1',
        'direccion_banco2',
        'cp_banco',
        'poblacion_banco',
        'cod_pais_banco',
        'ccc',
        'plazo_entrega',
        'cod_transportista',
        'cod_central_compras',
        'fecha_inicio_vacaciones',
        'fecha_fin_vacaciones',
        'facturacion_centralizada',
        'observaciones',
        'advertencia',
        'portes_pagados',
        'compra_minima',
        'su_cliente',
        'cliente_central_compra',
        'dia_pago1',
        'dia_pago2',
        'dia_pago3',
        'dia_vencimiento_vacaciones',
        'gln_facturas',
        'gln_pedidos',
        'iban',
        'swift',
        'criterio_de_caja',
        'tipo_persona',
        'motivo_baja',
        'telefono2',
        'telefono3',
        'telefono1_comentario',
        'telefono2_comentario',
        'telefono3_comentario',
        'fax_comentario',
        'facebook',
        'twitter',
        'youtube',
        'whatsapp',
        'latitud',
        'longitud',
        'tipo_operacion_iva',
        'inversion_sujeto_pasivo',
        'importe_portes_pagados',
        'valoracion_albaran',
        'rowguid',
    ];
}
